// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Myrmex.Modules.Wms.Infrastructure.Persistence;

#nullable disable

namespace Myrmex.Modules.Wms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20260611091510_AddStockKeepingUnitBaseUnitOfMeasure")]
    partial class AddStockKeepingUnitBaseUnitOfMeasure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wms")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.SkuBarcodes.SkuBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbology")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id")
                        .HasName("PK_wms_sku_barcodes");

                    b.HasIndex("StockKeepingUnitId")
                        .HasDatabaseName("IX_wms_sku_barcodes_stock_keeping_unit_id");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_sku_barcodes_value");

                    b.ToTable("sku_barcodes", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseUnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_stock_keeping_units");

                    b.HasIndex("BaseUnitOfMeasureId")
                        .HasDatabaseName("IX_wms_stock_keeping_units_base_unit_of_measure_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_stock_keeping_units_code");

                    b.ToTable("stock_keeping_units", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.UnitsOfMeasure.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_units_of_measure");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_units_of_measure_code");

                    b.ToTable("units_of_measure", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPickable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("StorageLocationStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StorageLocationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_wms_storage_locations");

                    b.HasIndex("StorageLocationStatusId")
                        .HasDatabaseName("IX_wms_storage_locations_storage_location_status_id");

                    b.HasIndex("StorageLocationTypeId")
                        .HasDatabaseName("IX_wms_storage_locations_storage_location_type_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_wms_storage_locations_warehouse_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("IX_wms_storage_locations_zone_id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_storage_locations_warehouse_id_code");

                    b.ToTable("storage_locations", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_storage_location_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_storage_location_statuses_code");

                    b.ToTable("storage_location_statuses", "wms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000101"),
                            Code = "AVAILABLE",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Storage location is available for operations.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Available",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000102"),
                            Code = "BLOCKED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Storage location is blocked for operations.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Blocked",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000103"),
                            Code = "MAINTENANCE",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Storage location is under maintenance.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Maintenance",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000104"),
                            Code = "INVENTORY_CHECK",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Storage location is under inventory check.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Inventory check",
                            SortOrder = 40
                        });
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_storage_location_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_storage_location_types_code");

                    b.ToTable("storage_location_types", "wms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000001"),
                            Code = "PALLET_RACK",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pallet rack storage location.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Pallet rack",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000002"),
                            Code = "SHELF",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Shelf or bin storage location.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Shelf",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000003"),
                            Code = "FLOOR",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Floor storage location.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Floor",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000004"),
                            Code = "STAGING",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Temporary staging location.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Staging",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000005"),
                            Code = "DOCK",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Receiving or shipping dock.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Dock",
                            SortOrder = 50
                        });
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_warehouses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_warehouses_code");

                    b.ToTable("warehouses", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.Zones.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_wms_zones");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_wms_zones_warehouse_id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_zones_warehouse_id_code");

                    b.ToTable("zones", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.SkuBarcodes.SkuBarcode", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", null)
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_sku_barcodes_stock_keeping_units_stock_keeping_unit_id");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Catalog.Domain.UnitsOfMeasure.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("BaseUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_stock_keeping_units_units_of_measure_base_unit_of_measure_id");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocationStatus", null)
                        .WithMany()
                        .HasForeignKey("StorageLocationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_storage_locations_storage_location_statuses_storage_location_status_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocationType", null)
                        .WithMany()
                        .HasForeignKey("StorageLocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_storage_locations_storage_location_types_storage_location_type_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_storage_locations_warehouses_warehouse_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.Zones.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_storage_locations_zones_zone_id");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.Zones.Zone", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_zones_warehouses_warehouse_id");
                });
#pragma warning restore 612, 618
        }
    }
}
