// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Myrmex.Modules.Wms.Infrastructure.Persistence;

#nullable disable

namespace Myrmex.Modules.Wms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20260727120911_LinesOnDeleteCascade")]
    partial class LinesOnDeleteCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wms")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.SkuBarcodes.SkuBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbology")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id")
                        .HasName("PK_wms_sku_barcodes");

                    b.HasIndex("StockKeepingUnitId")
                        .HasDatabaseName("IX_wms_sku_barcodes_stock_keeping_unit_id");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_sku_barcodes_value");

                    b.ToTable("sku_barcodes", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AreaSquareMetres")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<Guid>("BaseUnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LengthMetres")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("VolumeCubicMetres")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<decimal?>("WeightKilograms")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.HasKey("Id")
                        .HasName("PK_wms_stock_keeping_units");

                    b.HasIndex("BaseUnitOfMeasureId")
                        .HasDatabaseName("IX_wms_stock_keeping_units_base_unit_of_measure_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_stock_keeping_units_code");

                    b.ToTable("stock_keeping_units", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.UnitsOfMeasure.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_units_of_measure");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_units_of_measure_code");

                    b.ToTable("units_of_measure", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryBalances.InventoryBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_inventory_balances");

                    b.HasIndex("StorageLocationId")
                        .HasDatabaseName("IX_wms_inventory_balances_storage_location_id");

                    b.HasIndex("StockKeepingUnitId", "StorageLocationId")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_inventory_balances_stock_keeping_unit_id_storage_location_id");

                    b.ToTable("inventory_balances", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryCounts.InventoryCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CancelledByActorId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompletedByActorId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_wms_inventory_counts");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_wms_inventory_counts_created_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_wms_inventory_counts_status");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_wms_inventory_counts_warehouse_id");

                    b.ToTable("inventory_counts", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryCounts.InventoryCountLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AppliedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AppliedByActorId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("AppliedInventoryTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CountedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CountedByActorId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("CountedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("ExpectedBalanceVersion")
                        .HasMaxLength(8)
                        .HasColumnType("varbinary(8)");

                    b.Property<Guid>("InventoryCountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesInventoryCountLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SystemQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("VarianceQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id")
                        .HasName("PK_wms_inventory_count_lines");

                    b.HasIndex("AppliedInventoryTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_inventory_count_lines_applied_inventory_transaction_id")
                        .HasFilter("[AppliedInventoryTransactionId] IS NOT NULL");

                    b.HasIndex("InventoryCountId")
                        .HasDatabaseName("IX_wms_inventory_count_lines_inventory_count_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_wms_inventory_count_lines_status");

                    b.HasIndex("StockKeepingUnitId")
                        .HasDatabaseName("IX_wms_inventory_count_lines_stock_keeping_unit_id");

                    b.HasIndex("StorageLocationId")
                        .HasDatabaseName("IX_wms_inventory_count_lines_storage_location_id");

                    b.HasIndex("SupersedesInventoryCountLineId")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_inventory_count_lines_supersedes_inventory_count_line_id")
                        .HasFilter("[SupersedesInventoryCountLineId] IS NOT NULL");

                    b.HasIndex("InventoryCountId", "StockKeepingUnitId", "StorageLocationId")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_inventory_count_lines_current_pair")
                        .HasFilter("[IsCurrent] = CAST(1 AS bit)");

                    b.ToTable("inventory_count_lines", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransactions.InventoryLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InventoryTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_inventory_ledger_entries");

                    b.HasIndex("InventoryTransactionId");

                    b.HasIndex("StockKeepingUnitId")
                        .HasDatabaseName("IX_wms_inventory_ledger_entries_stock_keeping_unit_id");

                    b.HasIndex("StorageLocationId")
                        .HasDatabaseName("IX_wms_inventory_ledger_entries_storage_location_id");

                    b.ToTable("inventory_ledger_entries", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransactions.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_inventory_transactions");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_wms_inventory_transactions_occurred_at_utc");

                    b.ToTable("inventory_transactions", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransfers.InventoryTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DestinationWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("TransitStorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_inventory_transfers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_inventory_transfers_code");

                    b.HasIndex("DestinationWarehouseId")
                        .HasDatabaseName("IX_wms_inventory_transfers_destination_warehouse_id");

                    b.HasIndex("SourceWarehouseId")
                        .HasDatabaseName("IX_wms_inventory_transfers_source_warehouse_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_wms_inventory_transfers_status");

                    b.HasIndex("TransitStorageLocationId")
                        .HasDatabaseName("IX_wms_inventory_transfers_transit_storage_location_id");

                    b.ToTable("inventory_transfers", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransfers.InventoryTransferLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DestinationStorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryTransferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RequestedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("SourceStorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_inventory_transfer_lines");

                    b.HasIndex("DestinationStorageLocationId")
                        .HasDatabaseName("IX_wms_inventory_transfer_lines_destination_storage_location_id");

                    b.HasIndex("InventoryTransferId")
                        .HasDatabaseName("IX_wms_inventory_transfer_lines_inventory_transfer_id");

                    b.HasIndex("SourceStorageLocationId")
                        .HasDatabaseName("IX_wms_inventory_transfer_lines_source_storage_location_id");

                    b.HasIndex("StockKeepingUnitId")
                        .HasDatabaseName("IX_wms_inventory_transfer_lines_stock_keeping_unit_id");

                    b.ToTable("inventory_transfer_lines", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransfers.InventoryTransferMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FromStorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryTransferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryTransferLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ToStorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_inventory_transfer_movements");

                    b.HasIndex("FromStorageLocationId")
                        .HasDatabaseName("IX_wms_inventory_transfer_movements_from_storage_location_id");

                    b.HasIndex("InventoryTransactionId")
                        .HasDatabaseName("IX_wms_inventory_transfer_movements_inventory_transaction_id");

                    b.HasIndex("InventoryTransferId")
                        .HasDatabaseName("IX_wms_inventory_transfer_movements_inventory_transfer_id");

                    b.HasIndex("InventoryTransferLineId")
                        .HasDatabaseName("IX_wms_inventory_transfer_movements_inventory_transfer_line_id");

                    b.HasIndex("ToStorageLocationId")
                        .HasDatabaseName("IX_wms_inventory_transfer_movements_to_storage_location_id");

                    b.ToTable("inventory_transfer_movements", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Receiving.Domain.ReceivingOrders.ReceivingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("InventoryTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("ReceivingLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_wms_receiving_orders");

                    b.HasIndex("InventoryTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_receiving_orders_inventory_transaction_id")
                        .HasFilter("[InventoryTransactionId] IS NOT NULL");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_receiving_orders_number");

                    b.HasIndex("ReceivingLocationId")
                        .HasDatabaseName("IX_wms_receiving_orders_receiving_location_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_wms_receiving_orders_warehouse_id");

                    b.ToTable("receiving_orders", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Receiving.Domain.ReceivingOrders.ReceivingOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ReceivingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_receiving_order_lines");

                    b.HasIndex("StockKeepingUnitId")
                        .HasDatabaseName("IX_wms_receiving_order_lines_stock_keeping_unit_id");

                    b.HasIndex("ReceivingOrderId", "StockKeepingUnitId")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_receiving_order_lines_receiving_order_id_stock_keeping_unit_id");

                    b.ToTable("receiving_order_lines", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPickable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("StorageLocationStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StorageLocationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_wms_storage_locations");

                    b.HasIndex("StorageLocationStatusId")
                        .HasDatabaseName("IX_wms_storage_locations_storage_location_status_id");

                    b.HasIndex("StorageLocationTypeId")
                        .HasDatabaseName("IX_wms_storage_locations_storage_location_type_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_wms_storage_locations_warehouse_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("IX_wms_storage_locations_zone_id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_storage_locations_warehouse_id_code");

                    b.ToTable("storage_locations", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_storage_location_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_storage_location_statuses_code");

                    b.ToTable("storage_location_statuses", "wms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000101"),
                            Code = "AVAILABLE",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Storage location is available for operations.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Available",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000102"),
                            Code = "BLOCKED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Storage location is blocked for operations.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Blocked",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000103"),
                            Code = "MAINTENANCE",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Storage location is under maintenance.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Maintenance",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000104"),
                            Code = "INVENTORY_CHECK",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Storage location is under inventory check.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Inventory check",
                            SortOrder = 40
                        });
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_storage_location_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_storage_location_types_code");

                    b.ToTable("storage_location_types", "wms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000001"),
                            Code = "PALLET_RACK",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pallet rack storage location.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Pallet rack",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000002"),
                            Code = "SHELF",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Shelf or bin storage location.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Shelf",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000003"),
                            Code = "FLOOR",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Floor storage location.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Floor",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000004"),
                            Code = "STAGING",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Temporary staging location.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Staging",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000005"),
                            Code = "DOCK",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Receiving or shipping dock.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Dock",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000006"),
                            Code = "INTERNAL_TRANSIT",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "System storage location type for internal inventory transfer transit.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Internal transit",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000007"),
                            Code = "EXTERNAL_TRANSIT",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "System storage location type reserved for external inventory transfer transit.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "External transit",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = new Guid("018f0000-0000-7000-8000-000000000008"),
                            Code = "RECEIVING",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Storage location for receiving inventory.",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Receiving",
                            SortOrder = 80
                        });
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DefaultReceivingLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_wms_warehouses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_warehouses_code");

                    b.HasIndex("DefaultReceivingLocationId");

                    b.ToTable("warehouses", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.Zones.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_wms_zones");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_wms_zones_warehouse_id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_wms_zones_warehouse_id_code");

                    b.ToTable("zones", "wms");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.SkuBarcodes.SkuBarcode", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", null)
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_sku_barcodes_stock_keeping_units_stock_keeping_unit_id");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Catalog.Domain.UnitsOfMeasure.UnitOfMeasure", "BaseUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("BaseUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_stock_keeping_units_units_of_measure_base_unit_of_measure_id");

                    b.OwnsOne("Myrmex.Modules.Wms.Domain.ExternalImportState", "ImportState", b1 =>
                        {
                            b1.Property<Guid>("StockKeepingUnitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("DataVersion")
                                .HasMaxLength(128)
                                .HasColumnType("varbinary(128)")
                                .HasColumnName("ExternalDataVersion");

                            b1.Property<DateTimeOffset>("ImportedAtUtc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("LastImportedAtUtc");

                            b1.Property<Guid>("RefKey")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ExternalRefKey");

                            b1.HasKey("StockKeepingUnitId");

                            b1.HasIndex("RefKey")
                                .IsUnique()
                                .HasDatabaseName("UX_wms_stock_keeping_units_external_ref_key")
                                .HasFilter("[ExternalRefKey] IS NOT NULL");

                            b1.ToTable("stock_keeping_units", "wms");

                            b1.WithOwner()
                                .HasForeignKey("StockKeepingUnitId");
                        });

                    b.Navigation("BaseUnitOfMeasure");

                    b.Navigation("ImportState");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Catalog.Domain.UnitsOfMeasure.UnitOfMeasure", b =>
                {
                    b.OwnsOne("Myrmex.Modules.Wms.Domain.ExternalImportState", "ImportState", b1 =>
                        {
                            b1.Property<Guid>("UnitOfMeasureId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("DataVersion")
                                .HasMaxLength(128)
                                .HasColumnType("varbinary(128)")
                                .HasColumnName("ExternalDataVersion");

                            b1.Property<DateTimeOffset>("ImportedAtUtc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("LastImportedAtUtc");

                            b1.Property<Guid>("RefKey")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ExternalRefKey");

                            b1.HasKey("UnitOfMeasureId");

                            b1.HasIndex("RefKey")
                                .IsUnique()
                                .HasDatabaseName("UX_wms_units_of_measure_external_ref_key")
                                .HasFilter("[ExternalRefKey] IS NOT NULL");

                            b1.ToTable("units_of_measure", "wms");

                            b1.WithOwner()
                                .HasForeignKey("UnitOfMeasureId");
                        });

                    b.Navigation("ImportState");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryBalances.InventoryBalance", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_balances_stock_keeping_units_stock_keeping_unit_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_balances_storage_locations_storage_location_id");

                    b.Navigation("StockKeepingUnit");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryCounts.InventoryCount", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_counts_warehouses_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryCounts.InventoryCountLine", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransactions.InventoryTransaction", "AppliedInventoryTransaction")
                        .WithMany()
                        .HasForeignKey("AppliedInventoryTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_wms_inventory_count_lines_inventory_transactions_applied_inventory_transaction_id");

                    b.HasOne("Myrmex.Modules.Wms.Inventory.Domain.InventoryCounts.InventoryCount", "InventoryCount")
                        .WithMany("Lines")
                        .HasForeignKey("InventoryCountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_count_lines_inventory_counts_inventory_count_id");

                    b.HasOne("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_count_lines_stock_keeping_units_stock_keeping_unit_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_count_lines_storage_locations_storage_location_id");

                    b.HasOne("Myrmex.Modules.Wms.Inventory.Domain.InventoryCounts.InventoryCountLine", "SupersedesInventoryCountLine")
                        .WithOne("ReplacementInventoryCountLine")
                        .HasForeignKey("Myrmex.Modules.Wms.Inventory.Domain.InventoryCounts.InventoryCountLine", "SupersedesInventoryCountLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_wms_inventory_count_lines_inventory_count_lines_supersedes_inventory_count_line_id");

                    b.Navigation("AppliedInventoryTransaction");

                    b.Navigation("InventoryCount");

                    b.Navigation("StockKeepingUnit");

                    b.Navigation("StorageLocation");

                    b.Navigation("SupersedesInventoryCountLine");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransactions.InventoryLedgerEntry", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransactions.InventoryTransaction", "InventoryTransaction")
                        .WithMany("Entries")
                        .HasForeignKey("InventoryTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_ledger_entries_inventory_transactions_inventory_transaction_id");

                    b.HasOne("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_ledger_entries_stock_keeping_units_stock_keeping_unit_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_ledger_entries_storage_locations_storage_location_id");

                    b.Navigation("InventoryTransaction");

                    b.Navigation("StockKeepingUnit");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransfers.InventoryTransfer", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", "DestinationWarehouse")
                        .WithMany()
                        .HasForeignKey("DestinationWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfers_warehouses_destination_warehouse_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", "SourceWarehouse")
                        .WithMany()
                        .HasForeignKey("SourceWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfers_warehouses_source_warehouse_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", "TransitStorageLocation")
                        .WithMany()
                        .HasForeignKey("TransitStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_wms_inventory_transfers_storage_locations_transit_storage_location_id");

                    b.Navigation("DestinationWarehouse");

                    b.Navigation("SourceWarehouse");

                    b.Navigation("TransitStorageLocation");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransfers.InventoryTransferLine", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", "DestinationStorageLocation")
                        .WithMany()
                        .HasForeignKey("DestinationStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfer_lines_storage_locations_destination_storage_location_id");

                    b.HasOne("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransfers.InventoryTransfer", "InventoryTransfer")
                        .WithMany("Lines")
                        .HasForeignKey("InventoryTransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfer_lines_inventory_transfers_inventory_transfer_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", "SourceStorageLocation")
                        .WithMany()
                        .HasForeignKey("SourceStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfer_lines_storage_locations_source_storage_location_id");

                    b.HasOne("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfer_lines_stock_keeping_units_stock_keeping_unit_id");

                    b.Navigation("DestinationStorageLocation");

                    b.Navigation("InventoryTransfer");

                    b.Navigation("SourceStorageLocation");

                    b.Navigation("StockKeepingUnit");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransfers.InventoryTransferMovement", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", "FromStorageLocation")
                        .WithMany()
                        .HasForeignKey("FromStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfer_movements_storage_locations_from_storage_location_id");

                    b.HasOne("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransactions.InventoryTransaction", "InventoryTransaction")
                        .WithMany()
                        .HasForeignKey("InventoryTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfer_movements_inventory_transactions_inventory_transaction_id");

                    b.HasOne("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransfers.InventoryTransfer", "InventoryTransfer")
                        .WithMany("Movements")
                        .HasForeignKey("InventoryTransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfer_movements_inventory_transfers_inventory_transfer_id");

                    b.HasOne("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransfers.InventoryTransferLine", "InventoryTransferLine")
                        .WithMany()
                        .HasForeignKey("InventoryTransferLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfer_movements_inventory_transfer_lines_inventory_transfer_line_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", "ToStorageLocation")
                        .WithMany()
                        .HasForeignKey("ToStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_inventory_transfer_movements_storage_locations_to_storage_location_id");

                    b.Navigation("FromStorageLocation");

                    b.Navigation("InventoryTransaction");

                    b.Navigation("InventoryTransfer");

                    b.Navigation("InventoryTransferLine");

                    b.Navigation("ToStorageLocation");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Receiving.Domain.ReceivingOrders.ReceivingOrder", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransactions.InventoryTransaction", "InventoryTransaction")
                        .WithMany()
                        .HasForeignKey("InventoryTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_wms_receiving_orders_inventory_transactions_inventory_transaction_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", "ReceivingLocation")
                        .WithMany()
                        .HasForeignKey("ReceivingLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_receiving_orders_storage_locations_receiving_location_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_receiving_orders_warehouses_warehouse_id");

                    b.OwnsOne("Myrmex.Modules.Wms.Domain.ExternalImportState", "ImportState", b1 =>
                        {
                            b1.Property<Guid>("ReceivingOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("DataVersion")
                                .HasMaxLength(128)
                                .HasColumnType("varbinary(128)")
                                .HasColumnName("ExternalDataVersion");

                            b1.Property<DateTimeOffset>("ImportedAtUtc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("LastImportedAtUtc");

                            b1.Property<Guid>("RefKey")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ExternalRefKey");

                            b1.HasKey("ReceivingOrderId");

                            b1.HasIndex("RefKey")
                                .IsUnique()
                                .HasDatabaseName("UX_wms_receiving_orders_external_ref_key")
                                .HasFilter("[ExternalRefKey] IS NOT NULL");

                            b1.ToTable("receiving_orders", "wms");

                            b1.WithOwner()
                                .HasForeignKey("ReceivingOrderId");
                        });

                    b.Navigation("ImportState");

                    b.Navigation("InventoryTransaction");

                    b.Navigation("ReceivingLocation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Receiving.Domain.ReceivingOrders.ReceivingOrderLine", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Receiving.Domain.ReceivingOrders.ReceivingOrder", "ReceivingOrder")
                        .WithMany("Lines")
                        .HasForeignKey("ReceivingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_wms_receiving_order_lines_receiving_orders_receiving_order_id");

                    b.HasOne("Myrmex.Modules.Wms.Catalog.Domain.StockKeepingUnits.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_receiving_order_lines_stock_keeping_units_stock_keeping_unit_id");

                    b.Navigation("ReceivingOrder");

                    b.Navigation("StockKeepingUnit");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocationStatus", "StorageLocationStatus")
                        .WithMany()
                        .HasForeignKey("StorageLocationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_storage_locations_storage_location_statuses_storage_location_status_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocationType", "StorageLocationType")
                        .WithMany()
                        .HasForeignKey("StorageLocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_storage_locations_storage_location_types_storage_location_type_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_storage_locations_warehouses_warehouse_id");

                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.Zones.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_storage_locations_zones_zone_id");

                    b.Navigation("StorageLocationStatus");

                    b.Navigation("StorageLocationType");

                    b.Navigation("Warehouse");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.StorageLocations.StorageLocation", "DefaultReceivingLocation")
                        .WithMany()
                        .HasForeignKey("DefaultReceivingLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_wms_warehouses_storage_locations_default_receiving_location_id");

                    b.OwnsOne("Myrmex.Modules.Wms.Domain.ExternalImportState", "ImportState", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("DataVersion")
                                .HasMaxLength(128)
                                .HasColumnType("varbinary(128)")
                                .HasColumnName("ExternalDataVersion");

                            b1.Property<DateTimeOffset>("ImportedAtUtc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("LastImportedAtUtc");

                            b1.Property<Guid>("RefKey")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ExternalRefKey");

                            b1.HasKey("WarehouseId");

                            b1.HasIndex("RefKey")
                                .IsUnique()
                                .HasDatabaseName("UX_wms_warehouses_external_ref_key")
                                .HasFilter("[ExternalRefKey] IS NOT NULL");

                            b1.ToTable("warehouses", "wms");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.Navigation("DefaultReceivingLocation");

                    b.Navigation("ImportState");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Topology.Domain.Zones.Zone", b =>
                {
                    b.HasOne("Myrmex.Modules.Wms.Topology.Domain.Warehouses.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_wms_zones_warehouses_warehouse_id");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryCounts.InventoryCount", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryCounts.InventoryCountLine", b =>
                {
                    b.Navigation("ReplacementInventoryCountLine");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransactions.InventoryTransaction", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Inventory.Domain.InventoryTransfers.InventoryTransfer", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Myrmex.Modules.Wms.Receiving.Domain.ReceivingOrders.ReceivingOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
