<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Myrmex.AppDispatching\Myrmex.AppDispatching.csproj" />
    <ProjectReference Include="..\Myrmex.AspNetCore\Myrmex.AspNetCore.csproj" />
    <ProjectReference Include="..\Myrmex.Core\Myrmex.Core.csproj" />
    <ProjectReference Include="..\Myrmex.Modules.Wms\Myrmex.Modules.Wms.csproj" />
    <ProjectReference Include="..\Myrmex.Shared\Myrmex.Shared.csproj" />
  </ItemGroup>

</Project>
