services:
  myrmex-api:
    image: 192.168.1.55:5000/myrmex-api:${MYRMEX_TAG}
    container_name: myrmex-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ConnectionStrings__MyrmexDatabase: "${MYRMEX_DB_CONNECTION}"
      Myrmex__Wms__DemoData__Enabled: "true"
      Myrmex__Wms__DemoData__AllowClear: "true"
    ports:
      - "8204:8080"
      - "8304:8081"